security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:


        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
                    pattern:  ^/api/login
                    stateless: true
                    anonymous: true
                    form_login:
                        check_path:               /api/login_check
                        require_previous_session: false
                        username_parameter: username
                        password_parameter: password
                        success_handler:          lexik_jwt_authentication.handler.authentication_success
                        failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        
        api:
            pattern:   ^/api
            stateless: true
            anonymous: false
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            
            anonymous: ~
            pattern: ^/
            form_login:

                 default_target_path: /listes
            logout:
                path:   /logout
                target: /login


            



    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }